apiVersion: apps/v1
kind: Deployment
metadata:
  name: critical-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: critical
  template:
    metadata:
      labels:
        app: critical
    spec:
      priorityClassName: high-priority
      nodeSelector:
        node-type: correct
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
