apiVersion: v1
kind: Service
metadata:
  name: fortio-server
  namespace: app
  labels:
    app: fortio-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9999"
spec:
  selector:
    app: fortio-server
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: metrics
    port: 9999
    targetPort: 9999
