apiVersion: v1
kind: Service
metadata:
  name: fortio-client
  namespace: app
  labels:
    app: fortio-client
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9999"
spec:
  selector:
    app: fortio-client
  ports:
  - name: metrics
    port: 9999
    targetPort: 9999
