apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: kill-fortio-client
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
    - app
    labelSelectors:
      app: fortio-client
  duration: "30s"
